[package]
name = "nrtm-parser"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "(streaming) PEG parser for NRTMv2 and NRTMv3 event streams"
readme = "README.md"
repository = "https://github.com/wobcom/nrtm-parse"
keywords = ["nrtm","rpsl","parser","whois","routing"]
categories = ["network-programming", "encoding"]

[dependencies]
pest = "2.9.0"
pest_derive = "2.9.0"
tokio = { version = "1.53.1", optional = true }
tokio-util = { version = "0.7.19", optional = true, features = ["codec"] }
re-delimiter-codec = { version = "0.1.0", optional = true }
regex = { version = "1.13.1", optional = true }
futures-util = { version = "0.3.34", optional = true }
chardetng = { version = "1.0.0", optional = true }
encoding_rs = { version = "0.8.41", features = ["std"], optional = true }


[features]
default = [ ]
async-streaming = [ "dep:tokio-util", "dep:tokio", "dep:futures-util", "dep:re-delimiter-codec", "dep:regex", "dep:chardetng", "dep:encoding_rs" ]

[dev-dependencies]
tokio = { version = "1.53.1", features = ["fs", "macros", "rt" ] }
tokio-test = "0.4.5"
