WHITESPACE            = _{ " " | "\t" | (NEWLINE ~ line_cont) }
line_cont             = _{ " " | "\t" | "+" }
no_newline_whitespace = _{ " " | "\t" }
COMMENT               = _{ rpsl_comment | nrtm_comment }
rpsl_comment          = _{ "#" ~ (!NEWLINE ~ ANY)* }
nrtm_comment          = _{ "%" ~ (!NEWLINE ~ ANY)* }

// atomic, no whitespace accepted
num = @{ ASCII_DIGIT+ }

// NRTM
nrtm_add_verb     = _{ "ADD" }
nrtm_del_verb     = _{ "DEL" }
nrtm_any_verb     = _{ nrtm_add_verb | nrtm_del_verb }
rpsl_object_start = _{ NEWLINE ~ NEWLINE }
nrtm_line_comments = _{ (COMMENT ~ NEWLINE*)* }
leading_garbage   =  { (!nrtm_any_verb ~ ANY)* } // robust parsing requires us to ignore non-matching content
// v2
v2_add_operation = ${ nrtm_add_verb ~ rpsl_object_start ~ rpsl_object }
v2_del_operation = ${ nrtm_del_verb ~ rpsl_object_start ~ rpsl_object }
v2_operation     = ${ nrtm_line_comments ~ leading_garbage ~ (v2_add_operation | v2_del_operation) }
// v3
v3_add_operation = ${ nrtm_add_verb ~ no_newline_whitespace ~ num ~ rpsl_object_start ~ rpsl_object }
v3_del_operation = ${ nrtm_del_verb ~ no_newline_whitespace ~ num ~ rpsl_object_start ~ rpsl_object }
v3_operation     = ${ nrtm_line_comments ~ leading_garbage ~ (v3_add_operation | v3_del_operation) }


// RPSL
// rpsl is not completely parsed, can be passed on to rpsl-rs for complete parsing
// longest rpsl key is 14 chars, this length is hardcoded because it helps on the
// decidability of completeness (ie when to stop), whereas inf number of repetitions
// with + may lead to decidability issues with incomplete input (when streaming)
rpsl_key        = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "-" | "_"){,14} }
rpsl_kvsep      = @{ ":" }
free_form       = @{ (!attr_sep ~ ANY)* }
attr_sep        = @{ NEWLINE ~ (!line_cont ~ ANY) }
rpsl_attr       = ${ NEWLINE ~ rpsl_key ~ rpsl_kvsep ~ free_form }
rpsl_start_attr = ${ rpsl_key ~ rpsl_kvsep ~ free_form }
line_comment    = @{ NEWLINE ~ COMMENT }
rpsl_object     =  { rpsl_start_attr ~ ( line_comment | rpsl_attr )+ ~ NEWLINE ~ NEWLINE }
